"use client";

import { PageHeader } from "@/components/shared/PageHeader";
import { ReportCard } from "@/components/features/reports/ReportCard";
import {
  getSalesByStaff,
  getTopSellingCars,
  getServiceRevenue,
  getCustomerPurchases,
  getMonthlySales,
} from "@/services/reports";

export default function ReportsPage() {
  return (
    <div className="space-y-6">
      <PageHeader
        title="Reports"
        description="Business analytics and insights"
      />

      <div className="space-y-6">
        {/* Sales by Staff Member */}
        <ReportCard
          title="Sales by Staff Member"
          description="Total sales count and revenue generated by each salesperson"
          columns={[
            { header: "Staff Member", accessor: "staff_name" },
            { header: "Total Sales", accessor: "total_sales" },
            {
              header: "Total Revenue",
              accessor: ((row: any) =>
                `£${row.total_revenue.toLocaleString()}`) as any,
            },
          ]}
          onRun={getSalesByStaff}
        />

        {/* Top Selling Cars */}
        <ReportCard
          title="Top Selling Car Models"
          description="Most frequently sold vehicle makes and models with revenue"
          columns={[
            { header: "Make", accessor: "car_make" },
            { header: "Model", accessor: "car_model" },
            { header: "Times Sold", accessor: "times_sold" },
            {
              header: "Total Revenue",
              accessor: ((row: any) =>
                `£${row.total_revenue.toLocaleString()}`) as any,
            },
          ]}
          onRun={getTopSellingCars}
        />

        {/* Service Revenue Analysis */}
        <ReportCard
          title="Service Revenue by Vehicle"
          description="Total service costs and frequency for each vehicle model"
          columns={[
            { header: "Make", accessor: "car_make" },
            { header: "Model", accessor: "car_model" },
            { header: "Total Services", accessor: "total_services" },
            {
              header: "Total Cost",
              accessor: ((row: any) =>
                `£${row.total_cost.toLocaleString()}`) as any,
            },
          ]}
          onRun={getServiceRevenue}
        />

        {/* Customer Purchase History */}
        <ReportCard
          title="Customer Purchase History"
          description="Complete list of customer purchases with vehicle and price details"
          columns={[
            { header: "Customer", accessor: "customer_name" },
            { header: "Email", accessor: "email" },
            { header: "Vehicle", accessor: "car" },
            {
              header: "Sale Price",
              accessor: ((row: any) =>
                `£${row.sale_price.toLocaleString()}`) as any,
            },
            {
              header: "Sale Date",
              accessor: ((row: any) =>
                new Date(row.sale_date).toLocaleDateString("en-GB")) as any,
            },
          ]}
          onRun={getCustomerPurchases}
        />

        {/* Monthly Sales Report */}
        <ReportCard
          title="Monthly Sales Summary"
          description="Sales count and revenue aggregated by month"
          columns={[
            { header: "Month", accessor: "month" },
            { header: "Total Sales", accessor: "total_sales" },
            {
              header: "Total Revenue",
              accessor: ((row: any) =>
                `£${row.total_revenue.toLocaleString()}`) as any,
            },
          ]}
          onRun={getMonthlySales}
        />
      </div>
    </div>
  );
}
